In [2]:
import pandas as pd
df=pd.read_csv("online_retail_practice_sample.csv")
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [8]:
#11. create a separate DataFrame containing only InvoiceNo, StockCode, Description, Quantity, UnitPrice, CustomerID and Country.
df[['InvoiceNo','StockCode','Description','Quantity','UnitPrice','CustomerID','Country']]

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17296.0,Germany

In [10]:
#12.	Create a small DataFrame containing the first 10 transactions and save it as a separate variable.
df_sample=df.head(10).copy()
df_sample

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
5,561166,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,3,2011-02-28 16:38:00,4.07,12343.0,Spain
6,570510,POST,POSTAGE,4,2011-07-01 00:08:00,14.40,12767.0,United Kingdom
7,574557,POST,POSTAGE,1,2011-09-23 07:36:00,21.60,13566.0,France
8,572698,21977,PACK OF 60 PINK PAISLEY CAKE CASES,2,2011-03-20 10:39:00,0.55,14765.0,Germany
9,547022,71053,WHITE METAL LANTERN,7,2011-09-14 17:41:00,4.07,15256.0,EIRE

In [11]:
#13.	Generate descriptive statistics for numerical columns and explain what Quantity and UnitPrice reveal.
df.describe()

          Quantity    UnitPrice    CustomerID
count  1612.000000  1612.000000   1541.000000
mean      7.158189     5.523189  15201.415315
std       5.890089     5.191564   1693.230069
min     -15.000000     0.000000  12305.000000
25%       4.000000     2.200000  13708.000000
50%       8.000000     3.390000  15220.000000
75%      12.000000     7.650000  16640.000000
max      15.000000    21.600000  18196.000000

In [15]:
#14. Generate descriptive summaries for categorical columns such as Country and Description.
df[['Country','Description']].describe()

       Country Description
count     1599        1589
unique      10          22
top     France     POSTAGE
freq       178         143

In [19]:
#15. Display detailed DataFrame information and identify columns with missing entries.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1612 entries, 0 to 1611
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    1612 non-null   object
 1   StockCode    1612 non-null   object
 2   Description  1589 non-null   object
 3   Quantity     1612 non-null   int64
 4   InvoiceDate  1612 non-null   object
 5   UnitPrice    1612 non-null   float64
 6   CustomerID   1541 non-null   float64
 7   Country      1599 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 100.9+ KB

In [21]:
df.isnull().sum()

InvoiceNo       0
StockCode       0
Description    23
Quantity        0
InvoiceDate     0
UnitPrice       0
CustomerID     71
Country        13
dtype: int64

In [22]:
missing_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (
        df.isnull().sum() / len(df)
    ) * 100
})

missing_summary

             Missing_Count  Missing_Percentage
InvoiceNo                0            0.000000
StockCode                0            0.000000
Description             23            1.426799
Quantity                 0            0.000000
InvoiceDate              0            0.000000
UnitPrice                0            0.000000
CustomerID              71            4.404467
Country                 13            0.806452

In [29]:
#16. Determine the number of distinct invoice numbers, products, countries and identified customers.
print(df["InvoiceNo"].nunique)
print(df["StockCode"].nunique)
print(df["Country"].nunique)
print(df["CustomerID"].nunique)

<bound method IndexOpsMixin.nunique of 0        570338
1        574674
2        545052
3        567005
4        573512
         ...
1607     546730
1608     556479
1609    C541876
1610     553299
1611     537515
Name: InvoiceNo, Length: 1612, dtype: object>
<bound method IndexOpsMixin.nunique of 0        71053
1        21730
2       84029G
3        71053
4       84029G
         ...
1607     21730
1608     22423
1609     21730
1610    85123A
1611    85123A
Name: StockCode, Length: 1612, dtype: object>
<bound method IndexOpsMixin.nunique of 0            Sweden
1            Sweden
2       Netherlands
3             Spain
4            Sweden
           ...
1607          Spain
1608           EIRE
1609          Spain
1610       Portugal
1611        Germany
Name: Country, Length: 1612, dtype: object>
<bound method IndexOpsMixin.nunique of 0       16640.0
1       17154.0
2       16783.0
3       14222.0
4       16830.0
         ...
1607    16326.0
1608    13615.0
1609    16943.0
1610    17478.0
1611    17296.0
Name: CustomerID, Length: 1612, dtype: float64>

In [41]:
#17.	Display the unique values in Country and determine how many countries appear in the dataset.
df['Country'].unique()

array(['Sweden', 'Netherlands', 'Spain', 'United Kingdom', 'France',
       'Germany', 'EIRE', 'Portugal', 'Belgium', 'Australia', nan],
      dtype=object)

In [42]:
df['Country'].nunique()

10

In [44]:
#Alphabetical order
sorted(df["Country"].dropna().unique())

['Australia',
 'Belgium',
 'EIRE',
 'France',
 'Germany',
 'Netherlands',
 'Portugal',
 'Spain',
 'Sweden',
 'United Kingdom']

In [45]:
#18.	Count transactions recorded for each country and display the 10 most frequent countries.
df["Country"].value_counts()

Country
France            178
Spain             165
Australia         165
Belgium           164
Sweden            162
United Kingdom    160
Netherlands       158
EIRE              155
Portugal          147
Germany           145
Name: count, dtype: int64

In [47]:
#10 most frequent countries
df["Country"].value_counts().head(10)

Country
France            178
Spain             165
Australia         165
Belgium           164
Sweden            162
United Kingdom    160
Netherlands       158
EIRE              155
Portugal          147
Germany           145
Name: count, dtype: int64

In [48]:
#19.	Create a compact dataset summary containing row count, column count, unique products and unique invoices.
print(df.shape[0])
print(df.shape[1])
print(df['StockCode'].unique())
print(df['InvoiceNo'].unique())

1612
8
['71053' '21730' '84029G' 'POST' '21977' '22633' '21212' '22752' '22423'
 '79323P' '85123A' '84406B']
['570338' '574674' '545052' ... 'C555041' '567397' '570077']

In [51]:
print(df['StockCode'].nunique())
print(df['InvoiceNo'].nunique())

12
1574

In [62]:
#dataset for 19
data=pd.DataFrame({
    "Metrices":
    ["Rows:",
    "Columns:",
    "StockCode:",
    "InvoiceNo:"
    ],
    "Values":
    [
    df.shape[0],
    df.shape[1],
    df['StockCode'].nunique(),
    df['InvoiceNo'].nunique()
    ]
})
data

     Metrices  Values
0       Rows:    1612
1    Columns:       8
2  StockCode:      12
3  InvoiceNo:    1574

In [64]:
#20.	Export a basic dataset profile to a CSV file for documentation.
from pathlib import Path

output_folder = Path("Ecommerce_Data_Analysis.ipynb")
output_folder.mkdir(parents=True, exist_ok=True)