In [1]:
#1.	Import Pandas and load the Online Retail Excel dataset into a DataFrame named df.
import pandas as pd
data=pd.read_csv("online_retail_practice_sample.csv")
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden
...,...,...,...,...,...,...,...,...
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [2]:
#2.	Display the first 5 transaction records and identify what each row represents.
#3.	Display the last 10 records and inspect whether the final transactions look structurally consistent.

data.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden

In [3]:
data.tail(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1602,576798,22633,HAND WARMER UNION JACK,8,2011-03-20 15:46:00,2.10,16068.0,Australia
1603,549401,21730,GLASS STAR FROSTED T-LIGHT HOLDER,5,2011-05-25 22:09:00,3.40,13436.0,Portugal
1604,565607,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,1,2011-07-24 17:52:00,2.71,13346.0,Netherlands
1605,569476,22423,REGENCY CAKESTAND 3 TIER,4,2011-04-19 21:53:00,12.75,17314.0,Sweden
1606,C554322,21212,PACK OF 72 RETROSPOT CAKE CASES,-6,2011-08-16 02:22:00,0.55,18187.0,Sweden
1607,546730,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-09-20 00:21:00,4.25,16326.0,Spain
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE
1609,C541876,21730,GLASS STAR FROSTED T-LIGHT HOLDER,-7,2011-04-07 12:48:00,5.10,16943.0,Spain
1610,553299,85123A,WHITE HANGING HEART T-LIGHT HOLDER,8,2011-09-24 16:24:00,2.55,17478.0,Portugal
1611,537515,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2011-08-24 00:48:00,2.55,17296.0,Germany

In [4]:
#4.	Display 15 randomly selected transaction records to understand the variety of data.
data.sample(15,random_state=42)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
29,565045,22752,SET 7 BABUSHKA NESTING BOXES,8,2011-10-05 07:59:00,7.65,17321.0,Netherlands
259,544497,POST,POSTAGE,2,2010-12-10 14:46:00,21.60,15411.0,France
383,539123,71053,WHITE METAL LANTERN,12,2011-02-09 04:06:00,4.07,14097.0,France
425,565669,79323P,PINK CHERRY LIGHTS,14,2011-07-13 11:38:00,5.40,14394.0,EIRE
239,559785,71053,WHITE METAL LANTERN,8,2011-08-20 18:01:00,4.07,17429.0,Sweden
787,562769,21977,PACK OF 60 PINK PAISLEY CAKE CASES,11,2011-03-16 12:30:00,0.66,12969.0,Australia
1471,544897,21977,PACK OF 60 PINK PAISLEY CAKE CASES,8,2011-07-18 18:26:00,0.55,18175.0,Portugal
497,561669,21730,GLASS STAR FROSTED T-LIGHT HOLDER,8,2011-02-01 01:20:00,4.25,14894.0,Spain
495,566207,21212,PACK OF 72 RETROSPOT CAKE CASES,11,2011-08-29 00:28:00,0.55,14557.0,France
754,568872,84406B,CREAM CUPID HEARTS COAT HANGER,12,2011-09-12 09:05:00,3.30,14377.0,United Kingdom
411,572532,21977,PACK OF 60 PINK PAISLEY CAKE CASES,1,2011-07-20 17:18:00,0.55,16634.0,Germany
1581,552090,21730,GLASS STAR FROSTED T-LIGHT HOLDER,9,2011-01-19 21:03:00,5.10,13181.0,France
720,C537033,22752,SET 7 BABUSHKA NESTING BOXES,-5,2011-08-03 23:56:00,7.65,16639.0,United Kingdom
247,576014,85123A,WHITE HANGING HEART T-LIGHT HOLDER,5,2011-06-11 17:56:00,2.04,12691.0,United Kingdom
567,547774,79323P,PINK CHERRY LIGHTS,13,2011-01-24 11:59:00,5.40,14055.0,Netherlands

In [5]:
data.shape

(1612, 8)

In [6]:
#6.	Display all column names and identify the columns needed to analyze revenue.
data.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [7]:
#7.	Display the data type of every column and identify any unsuitable data types.
data.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [12]:
#8.	Determine how many rows and columns the original dataset contains.
data.shape[1]

8

In [11]:
data.shape[0]

1612

In [13]:
#9.	Display the first 20 product descriptions and identify examples of different products.
data["Description"].head(20)

0                     WHITE METAL LANTERN
1       GLASS STAR FROSTED T-LIGHT HOLDER
2     KNITTED UNION FLAG HOT WATER BOTTLE
3                     WHITE METAL LANTERN
4     KNITTED UNION FLAG HOT WATER BOTTLE
5     KNITTED UNION FLAG HOT WATER BOTTLE
6                                 POSTAGE
7                                 POSTAGE
8      PACK OF 60 PINK PAISLEY CAKE CASES
9                     WHITE METAL LANTERN
10                 HAND WARMER UNION JACK
11        PACK OF 72 RETROSPOT CAKE CASES
12                                POSTAGE
13           SET 7 BABUSHKA NESTING BOXES
14      GLASS STAR FROSTED T-LIGHT HOLDER
15     PACK OF 60 PINK PAISLEY CAKE CASES
16                                POSTAGE
17               REGENCY CAKESTAND 3 TIER
18                     PINK CHERRY LIGHTS
19               REGENCY CAKESTAND 3 TIER
Name: Description, dtype: object

In [14]:
data["Description"].head(20).tolist()

['WHITE METAL LANTERN',
 'GLASS STAR FROSTED T-LIGHT HOLDER',
 'KNITTED UNION FLAG HOT WATER BOTTLE',
 'WHITE METAL LANTERN',
 'KNITTED UNION FLAG HOT WATER BOTTLE',
 'KNITTED UNION FLAG HOT WATER BOTTLE',
 'POSTAGE',
 'POSTAGE',
 'PACK OF 60 PINK PAISLEY CAKE CASES',
 'WHITE METAL LANTERN',
 'HAND WARMER UNION JACK',
 'PACK OF 72 RETROSPOT CAKE CASES',
 'POSTAGE',
 'SET 7 BABUSHKA NESTING BOXES',
 'GLASS STAR FROSTED T-LIGHT HOLDER',
 'PACK OF 60 PINK PAISLEY CAKE CASES',
 'POSTAGE',
 'REGENCY CAKESTAND 3 TIER',
 'PINK CHERRY LIGHTS',
 'REGENCY CAKESTAND 3 TIER']

In [15]:
data["Description"].dropna().drop_duplicates().head(20)

0                        WHITE METAL LANTERN
1          GLASS STAR FROSTED T-LIGHT HOLDER
2        KNITTED UNION FLAG HOT WATER BOTTLE
6                                    POSTAGE
8         PACK OF 60 PINK PAISLEY CAKE CASES
10                    HAND WARMER UNION JACK
11           PACK OF 72 RETROSPOT CAKE CASES
13              SET 7 BABUSHKA NESTING BOXES
17                  REGENCY CAKESTAND 3 TIER
18                        PINK CHERRY LIGHTS
20        WHITE HANGING HEART T-LIGHT HOLDER
36            CREAM CUPID HEARTS COAT HANGER
286      PACK OF 60 PINK PAISLEY CAKE CASES
505          CREAM CUPID HEARTS COAT HANGER
597            SET 7 BABUSHKA NESTING BOXES
634      WHITE HANGING HEART T-LIGHT HOLDER
637     KNITTED UNION FLAG HOT WATER BOTTLE
751                                 POSTAGE
784                  HAND WARMER UNION JACK
922                      PINK CHERRY LIGHTS
Name: Description, dtype: object

In [16]:
#10.	Write a short business summary explaining what the dataset contains and what the company wants to learn.
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1612 entries, 0 to 1611
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   InvoiceNo    1612 non-null   object
 1   StockCode    1612 non-null   object
 2   Description  1589 non-null   object
 3   Quantity     1612 non-null   int64
 4   InvoiceDate  1612 non-null   object
 5   UnitPrice    1612 non-null   float64
 6   CustomerID   1541 non-null   float64
 7   Country      1599 non-null   object
dtypes: float64(2), int64(1), object(5)
memory usage: 100.9+ KB