In [6]:
#31.	Create a working copy of the original DataFrame and retain the untouched source as df_raw.
import pandas as pd
df = pd.read_csv("Online_Retail_Practice_Sample.csv")
df_raw = df.copy()
df = df_raw.copy()
print("Original dataset:")
display(df_raw.head())
print("Working dataset:")
display(df.head())
print("Original shape:", df_raw.shape)
print("Working shape:", df.shape)

Original dataset:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden

Working dataset:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden

Original shape: (1612, 8)
Working shape: (1612, 8)

In [7]:
#32.	Rename the Description column to ProductDescription in your working copy.
df = df.rename(columns={
    "Description": "ProductDescription"
})
print("Updated column names:")
print(df.columns.tolist())
display(df.head())

Updated column names:
['InvoiceNo', 'StockCode', 'ProductDescription', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

,InvoiceNo,StockCode,ProductDescription,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,570338,71053,WHITE METAL LANTERN,7,2011-09-15 15:26:00,4.07,16640.0,Sweden
1,574674,21730,GLASS STAR FROSTED T-LIGHT HOLDER,14,2011-06-05 08:10:00,4.25,17154.0,Sweden
2,545052,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,0,2011-07-24 03:45:00,3.39,16783.0,Netherlands
3,567005,71053,WHITE METAL LANTERN,12,2011-09-04 16:55:00,3.39,14222.0,Spain
4,573512,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,15,2011-02-23 13:40:00,3.39,16830.0,Sweden

In [8]:
#33.	Create a Revenue column by multiplying Quantity by UnitPrice, preserving the original signed quantity.
df["Revenue"] = df["Quantity"] * df["UnitPrice"]
display(df[[
    "InvoiceNo",
    "ProductDescription",
    "Quantity",
    "UnitPrice",
    "Revenue"
]].head(10))

  InvoiceNo                   ProductDescription  Quantity  UnitPrice  Revenue
0    570338                  WHITE METAL LANTERN         7       4.07    28.49
1    574674    GLASS STAR FROSTED T-LIGHT HOLDER        14       4.25    59.50
2    545052  KNITTED UNION FLAG HOT WATER BOTTLE         0       3.39     0.00
3    567005                  WHITE METAL LANTERN        12       3.39    40.68
4    573512  KNITTED UNION FLAG HOT WATER BOTTLE        15       3.39    50.85
5    561166  KNITTED UNION FLAG HOT WATER BOTTLE         3       4.07    12.21
6    570510                              POSTAGE         4      14.40    57.60
7    574557                              POSTAGE         1      21.60    21.60
8    572698   PACK OF 60 PINK PAISLEY CAKE CASES         2       0.55     1.10
9    547022                  WHITE METAL LANTERN         7       4.07    28.49

In [10]:
#34.	Create a TransactionType column to classify records as cancellation, return, positive sale or other/invalid, using documented rules.
import numpy as np
conditions = [
    df["InvoiceNo"].isna(),
    df["InvoiceNo"].astype("string").str.startswith(
        "C", na=False
    ),
    df["Quantity"].isna() | (df["Quantity"] == 0),
    df["Quantity"] < 0,
    df["Quantity"] > 0
]
categories = [
    "Other/invalid",
    "Cancellation",
    "Other/invalid",
    "Return",
    "Positive sale"
]
df["TransactionType"] = np.select(
    conditions,
    categories,
    default="Other/invalid"
)
display(df[[
    "InvoiceNo",
    "ProductDescription",
    "Quantity",
    "UnitPrice",
    "Revenue",
    "TransactionType"
]].head(15))

,InvoiceNo,ProductDescription,Quantity,UnitPrice,Revenue,TransactionType
0,570338,WHITE METAL LANTERN,7,4.07,28.49,Positive sale
1,574674,GLASS STAR FROSTED T-LIGHT HOLDER,14,4.25,59.50,Positive sale
2,545052,KNITTED UNION FLAG HOT WATER BOTTLE,0,3.39,0.00,Other/invalid
3,567005,WHITE METAL LANTERN,12,3.39,40.68,Positive sale
4,573512,KNITTED UNION FLAG HOT WATER BOTTLE,15,3.39,50.85,Positive sale
5,561166,KNITTED UNION FLAG HOT WATER BOTTLE,3,4.07,12.21,Positive sale
6,570510,POSTAGE,4,14.40,57.60,Positive sale
7,574557,POSTAGE,1,21.60,21.60,Positive sale
8,572698,PACK OF 60 PINK PAISLEY CAKE CASES,2,0.55,1.10,Positive sale
9,547022,WHITE METAL LANTERN,7,4.07,28.49,Positive sale
10,567596,HAND WARMER UNION JACK,15,1.68,25.20,Positive sale
11,572459,PACK OF 72 RETROSPOT CAKE CASES,7,0.44,3.08,Positive sale
12,562436,POSTAGE,1,18.00,18.00,Positive sale
13,580539,SET 7 BABUSHKA NESTING BOXES,8,7.65,61.20,Positive sale
14,540057,GLASS STAR FROSTED T-LIGHT HOLDER,5,3.40,17.00,Positive sale

In [11]:
#35.	Create an IsIdentifiedCustomer column that indicates whether CustomerID is available.
df["IsIdentifiedCustomer"] = df["CustomerID"].notna()
display(df[[
    "CustomerID",
    "IsIdentifiedCustomer"
]].head(15))

    CustomerID  IsIdentifiedCustomer
0      16640.0                  True
1      17154.0                  True
2      16783.0                  True
3      14222.0                  True
4      16830.0                  True
5      12343.0                  True
6      12767.0                  True
7      13566.0                  True
8      14765.0                  True
9      15256.0                  True
10     15220.0                  True
11     12868.0                  True
12     13127.0                  True
13     13152.0                  True
14     12683.0                  True

In [12]:
#36.	Convert InvoiceDate to a proper Pandas datetime data type.
df["InvoiceDate"] = pd.to_datetime(
    df["InvoiceDate"],
    errors="coerce"
)
print("InvoiceDate data type:")
print(df["InvoiceDate"].dtype)
display(df[["InvoiceNo", "InvoiceDate"]].head(10))

InvoiceDate data type:
datetime64[ns]

  InvoiceNo         InvoiceDate
0    570338 2011-09-15 15:26:00
1    574674 2011-06-05 08:10:00
2    545052 2011-07-24 03:45:00
3    567005 2011-09-04 16:55:00
4    573512 2011-02-23 13:40:00
5    561166 2011-02-28 16:38:00
6    570510 2011-07-01 00:08:00
7    574557 2011-09-23 07:36:00
8    572698 2011-03-20 10:39:00
9    547022 2011-09-14 17:41:00

In [13]:
#37.	Convert InvoiceNo, StockCode and Country to suitable string data types.
string_columns = [
    "InvoiceNo",
    "StockCode",
    "Country"
]
for column in string_columns:
    df[column] = df[column].astype("string")
print("Updated data types:")
print(df[string_columns].dtypes)

Updated data types:
InvoiceNo    string[python]
StockCode    string[python]
Country      string[python]
dtype: object

In [14]:
#38.	Reorder columns so transaction identifiers and dates appear before product, customer and financial information.
priority_columns = [
    "InvoiceNo",
    "InvoiceDate",
    "StockCode",
    "ProductDescription",
    "CustomerID",
    "Country",
    "Quantity",
    "UnitPrice",
    "Revenue",
    "TransactionType",
    "IsIdentifiedCustomer"
]
remaining_columns = [
    column for column in df.columns
    if column not in priority_columns
]
df = df[priority_columns + remaining_columns]
print("Reordered columns:")
print(df.columns.tolist())
display(df.head())

Reordered columns:
['InvoiceNo', 'InvoiceDate', 'StockCode', 'ProductDescription', 'CustomerID', 'Country', 'Quantity', 'UnitPrice', 'Revenue', 'TransactionType', 'IsIdentifiedCustomer']

,InvoiceNo,InvoiceDate,StockCode,ProductDescription,CustomerID,Country,Quantity,UnitPrice,Revenue,TransactionType,IsIdentifiedCustomer
0,570338,2011-09-15 15:26:00,71053,WHITE METAL LANTERN,16640.0,Sweden,7,4.07,28.49,Positive sale,True
1,574674,2011-06-05 08:10:00,21730,GLASS STAR FROSTED T-LIGHT HOLDER,17154.0,Sweden,14,4.25,59.50,Positive sale,True
2,545052,2011-07-24 03:45:00,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,16783.0,Netherlands,0,3.39,0.00,Other/invalid,True
3,567005,2011-09-04 16:55:00,71053,WHITE METAL LANTERN,14222.0,Spain,12,3.39,40.68,Positive sale,True
4,573512,2011-02-23 13:40:00,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,16830.0,Sweden,15,3.39,50.85,Positive sale,True

In [15]:
#39.	Sort the working dataset by InvoiceDate and then by InvoiceNo.
df = df.sort_values(
    by=["InvoiceDate", "InvoiceNo"],
    ascending=[True, True],
    na_position="last"
)
display(df[[
    "InvoiceDate",
    "InvoiceNo",
    "ProductDescription",
    "Quantity",
    "UnitPrice",
    "Revenue"
]].head(20))

,InvoiceDate,InvoiceNo,ProductDescription,Quantity,UnitPrice,Revenue
1523,2010-12-01 00:05:00,569444,WHITE METAL LANTERN,15,3.39,50.85
122,2010-12-01 02:26:00,C543863,CREAM CUPID HEARTS COAT HANGER,-13,2.75,-35.75
409,2010-12-01 03:57:00,568184,CREAM CUPID HEARTS COAT HANGER,3,2.20,6.60
78,2010-12-01 06:06:00,C551232,WHITE METAL LANTERN,-7,4.07,-28.49
1312,2010-12-01 21:38:00,536850,REGENCY CAKESTAND 3 TIER,9,10.20,91.80
119,2010-12-01 23:01:00,544302,PINK CHERRY LIGHTS,15,5.40,81.00
699,2010-12-02 00:25:00,545362,CREAM CUPID HEARTS COAT HANGER,10,2.20,22.00
1028,2010-12-02 01:38:00,C541990,CREAM CUPID HEARTS COAT HANGER,-9,2.75,-24.75
408,2010-12-02 06:09:00,565012,POSTAGE,10,14.40,144.00
1184,2010-12-02 12:58:00,550375,WHITE METAL LANTERN,10,4.07,40.70
1091,2010-12-02 17:14:00,574089,POSTAGE,6,14.40,86.40
116,2010-12-03 00:20:00,541529,SET 7 BABUSHKA NESTING BOXES,7,7.65,53.55
1441,2010-12-03 04:15:00,554502,WHITE HANGING HEART T-LIGHT HOLDER,5,3.06,15.30
765,2010-12-03 04:50:00,563656,REGENCY CAKESTAND 3 TIER,12,12.75,153.00
468,2010-12-03 13:48:00,549594,POSTAGE,13,18.00,234.00
1565,2010-12-03 19:55:00,556513,SET 7 BABUSHKA NESTING BOXES,8,7.65,61.20
1072,2010-12-04 02:03:00,538332,PACK OF 72 RETROSPOT CAKE CASES,7,0.55,3.85
899,2010-12-04 13:37:00,558283,SET 7 BABUSHKA NESTING BOXES,14,9.18,128.52
897,2010-12-05 03:08:00,554306,POSTAGE,14,18.00,252.00
356,2010-12-05 03:21:00,542556,REGENCY CAKESTAND 3 TIER,8,12.75,102.00

In [16]:
#40.	Reset the DataFrame index after sorting and verify that the new index is sequential.
df = df.reset_index(drop=True)
print("First 10 index values:")
print(df.index[:10].tolist())
print("Is the index sequential?")
print(df.index.equals(pd.RangeIndex(start=0, stop=len(df))))
print("Final dataset shape:", df.shape)
display(df.head(10))

First 10 index values:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Is the index sequential?
True
Final dataset shape: (1612, 11)

,InvoiceNo,InvoiceDate,StockCode,ProductDescription,CustomerID,Country,Quantity,UnitPrice,Revenue,TransactionType,IsIdentifiedCustomer
0,569444,2010-12-01 00:05:00,71053,WHITE METAL LANTERN,13845.0,Germany,15,3.39,50.85,Positive sale,True
1,C543863,2010-12-01 02:26:00,84406B,CREAM CUPID HEARTS COAT HANGER,14319.0,France,-13,2.75,-35.75,Cancellation,True
2,568184,2010-12-01 03:57:00,84406B,CREAM CUPID HEARTS COAT HANGER,15058.0,France,3,2.20,6.60,Positive sale,True
3,C551232,2010-12-01 06:06:00,71053,WHITE METAL LANTERN,12472.0,Spain,-7,4.07,-28.49,Cancellation,True
4,536850,2010-12-01 21:38:00,22423,REGENCY CAKESTAND 3 TIER,12972.0,Sweden,9,10.20,91.80,Positive sale,True
5,544302,2010-12-01 23:01:00,79323P,PINK CHERRY LIGHTS,12861.0,Spain,15,5.40,81.00,Positive sale,True
6,545362,2010-12-02 00:25:00,84406B,CREAM CUPID HEARTS COAT HANGER,14485.0,Belgium,10,2.20,22.00,Positive sale,True
7,C541990,2010-12-02 01:38:00,84406B,CREAM CUPID HEARTS COAT HANGER,13364.0,Netherlands,-9,2.75,-24.75,Cancellation,True
8,565012,2010-12-02 06:09:00,POST,POSTAGE,14486.0,Spain,10,14.40,144.00,Positive sale,True
9,550375,2010-12-02 12:58:00,71053,WHITE METAL LANTERN,13058.0,Germany,10,4.07,40.70,Positive sale,True