In [2]:
#21.	Select and display only InvoiceNo and InvoiceDate for all transactions.
import pandas as pd
df=pd.read_csv("online_retail_practice_sample.csv")
df[['InvoiceNo', 'InvoiceDate']]

     InvoiceNo          InvoiceDate
0       570338  2011-09-15 15:26:00
1       574674  2011-06-05 08:10:00
2       545052  2011-07-24 03:45:00
3       567005  2011-09-04 16:55:00
4       573512  2011-02-23 13:40:00
...        ...                  ...
1607    546730  2011-09-20 00:21:00
1608    556479  2011-11-13 09:05:00
1609   C541876  2011-04-07 12:48:00
1610    553299  2011-09-24 16:24:00
1611    537515  2011-08-24 00:48:00

[1612 rows x 2 columns]

In [3]:
#22.	Retrieve a transaction at a specified row position using iloc and explain the difference between row position and index label.
transaction = df.iloc[5]
print(transaction)

InvoiceNo                                   561166
StockCode                                   84029G
Description    KNITTED UNION FLAG HOT WATER BOTTLE
Quantity                                         3
InvoiceDate                    2011-02-28 16:38:00
UnitPrice                                     4.07
CustomerID                                 12343.0
Country                                      Spain
Name: 5, dtype: object

In [4]:
#23.	Use loc to retrieve selected columns for a chosen range of index labels.
result = df.loc[0:4, ["InvoiceNo", "Description", "Quantity", "UnitPrice"]]
print(result)

  InvoiceNo                          Description  Quantity  UnitPrice
0    570338                  WHITE METAL LANTERN         7       4.07
1    574674    GLASS STAR FROSTED T-LIGHT HOLDER        14       4.25
2    545052  KNITTED UNION FLAG HOT WATER BOTTLE         0       3.39
3    567005                  WHITE METAL LANTERN        12       3.39
4    573512  KNITTED UNION FLAG HOT WATER BOTTLE        15       3.39

In [6]:
df.loc[5:10, ["InvoiceNo", "StockCode", "Country"]]

   InvoiceNo StockCode         Country
5     561166    84029G           Spain
6     570510      POST  United Kingdom
7     574557      POST          France
8     572698     21977         Germany
9     547022     71053            EIRE
10    567596     22633          France

In [7]:
#24.	Filter transactions where Quantity is greater than 10.
filtered_df = df[df["Quantity"] > 10]
print(filtered_df)

     InvoiceNo StockCode                          Description  Quantity  \
1       574674     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
3       567005     71053                  WHITE METAL LANTERN        12
4       573512    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        15
10      567596     22633               HAND WARMER UNION JACK        15
18      580659    79323P                   PINK CHERRY LIGHTS        15
...        ...       ...                                  ...       ...
1593    560762     21730    GLASS STAR FROSTED T-LIGHT HOLDER        11
1595    564607      POST                              POSTAGE        15
1601    540834      POST                              POSTAGE        14
1607    546730     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
1608    556479     22423             REGENCY CAKESTAND 3 TIER        13

              InvoiceDate  UnitPrice  CustomerID         Country
1     2011-06-05 08:10:00       4.25     17154.0          Sweden
3     2011-09-04 16:55:00       3.39     14222.0           Spain
4     2011-02-23 13:40:00       3.39     16830.0          Sweden
10    2011-07-24 14:21:00       1.68     15220.0          France
18    2011-06-11 21:15:00       8.10     18019.0          Sweden
...                   ...        ...         ...             ...
1593  2011-07-22 02:33:00       4.25     15530.0         Belgium
1595  2011-07-02 04:57:00      18.00     13500.0     Netherlands
1601  2011-01-26 11:06:00      21.60     13594.0  United Kingdom
1607  2011-09-20 00:21:00       4.25     16326.0           Spain
1608  2011-11-13 09:05:00      12.75     13615.0            EIRE

[527 rows x 8 columns]

In [8]:
#25.	Find transactions where UnitPrice is greater than £50.
filtered_df = df[df["UnitPrice"] > 50]
print(filtered_df)

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

In [9]:
#26.	Retrieve all transactions belonging to a specified country using a Boolean condition.
uk_transactions = df[df["Country"] == "United Kingdom"]
print(uk_transactions)

     InvoiceNo StockCode                          Description  Quantity  \
6       570510      POST                              POSTAGE         4
42      575608    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         8
69      566686     22423             REGENCY CAKESTAND 3 TIER        13
71      561128     22633               HAND WARMER UNION JACK         6
79      557907     22423             REGENCY CAKESTAND 3 TIER         5
...        ...       ...                                  ...       ...
1566    540156      POST                              POSTAGE         1
1571    575154      POST                              POSTAGE         8
1583    574808    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         5
1598    567397     71053                  WHITE METAL LANTERN         8
1601    540834      POST                              POSTAGE        14

              InvoiceDate  UnitPrice  CustomerID         Country
6     2011-07-01 00:08:00      14.40     12767.0  United Kingdom
42    2011-05-14 00:18:00       4.07     12560.0  United Kingdom
69    2011-06-14 08:46:00      12.75     15782.0  United Kingdom
71    2011-09-01 14:03:00       2.10     15231.0  United Kingdom
79    2011-06-16 06:13:00      15.30     15131.0  United Kingdom
...                   ...        ...         ...             ...
1566  2011-02-17 08:49:00      18.00     14542.0  United Kingdom
1571  2011-05-14 16:00:00      18.00     14689.0  United Kingdom
1583  2010-12-10 10:43:00       4.07     16508.0  United Kingdom
1598  2011-03-13 19:34:00       3.39     17260.0  United Kingdom
1601  2011-01-26 11:06:00      21.60     13594.0  United Kingdom

[160 rows x 8 columns]

In [10]:
country_transactions = df[df["Country"] == "Germany"]
print(country_transactions)

     InvoiceNo StockCode                          Description  Quantity  \
8       572698     21977   PACK OF 60 PINK PAISLEY CAKE CASES         2
21      579630    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        15
27      563081     21212      PACK OF 72 RETROSPOT CAKE CASES         1
36      562703    84406B       CREAM CUPID HEARTS COAT HANGER         7
45      573768    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        11
...        ...       ...                                  ...       ...
1523    569444     71053                  WHITE METAL LANTERN        15
1545    544682      POST                              POSTAGE        13
1556    578858    79323P                   PINK CHERRY LIGHTS        12
1570    567929    79323P                   PINK CHERRY LIGHTS         4
1611    537515    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6

              InvoiceDate  UnitPrice  CustomerID  Country
8     2011-03-20 10:39:00       0.55     14765.0  Germany
21    2011-12-08 18:19:00       3.39     13148.0  Germany
27    2011-11-23 02:52:00       0.55     13162.0  Germany
36    2011-09-25 09:35:00       2.75     16558.0  Germany
45    2011-10-13 05:03:00       4.07     17136.0  Germany
...                   ...        ...         ...      ...
1523  2010-12-01 00:05:00       3.39     13845.0  Germany
1545  2011-01-23 04:36:00      18.00     12987.0  Germany
1556  2010-12-21 03:44:00       6.75     12960.0  Germany
1570  2011-01-17 05:46:00       6.75     13703.0  Germany
1611  2011-08-24 00:48:00       2.55     17296.0  Germany

[145 rows x 8 columns]

In [11]:
#27.	Use isin to find transactions from the five countries with the highest transaction counts.
top_5_countries = df["Country"].value_counts().head(5).index
filtered_df = df[df["Country"].isin(top_5_countries)]
print(filtered_df)

     InvoiceNo StockCode                          Description  Quantity  \
0       570338     71053                  WHITE METAL LANTERN         7
1       574674     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
3       567005     71053                  WHITE METAL LANTERN        12
4       573512    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        15
5       561166    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         3
...        ...       ...                                  ...       ...
1602    576798     22633               HAND WARMER UNION JACK         8
1605    569476     22423             REGENCY CAKESTAND 3 TIER         4
1606   C554322     21212      PACK OF 72 RETROSPOT CAKE CASES        -6
1607    546730     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
1609   C541876     21730    GLASS STAR FROSTED T-LIGHT HOLDER        -7

              InvoiceDate  UnitPrice  CustomerID    Country
0     2011-09-15 15:26:00       4.07     16640.0     Sweden
1     2011-06-05 08:10:00       4.25     17154.0     Sweden
3     2011-09-04 16:55:00       3.39     14222.0      Spain
4     2011-02-23 13:40:00       3.39     16830.0     Sweden
5     2011-02-28 16:38:00       4.07     12343.0      Spain
...                   ...        ...         ...        ...
1602  2011-03-20 15:46:00       2.10     16068.0  Australia
1605  2011-04-19 21:53:00      12.75     17314.0     Sweden
1606  2011-08-16 02:22:00       0.55     18187.0     Sweden
1607  2011-09-20 00:21:00       4.25     16326.0      Spain
1609  2011-04-07 12:48:00       5.10     16943.0      Spain

[834 rows x 8 columns]

In [15]:
#28.	Use between to retrieve transactions with quantities between 5 and 20 inclusive.
filtered_df = df[df["Quantity"].between(5, 20)]
print(filtered_df)
print("Total matching transactions:", len(filtered_df))

     InvoiceNo StockCode                          Description  Quantity  \
0       570338     71053                  WHITE METAL LANTERN         7
1       574674     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
3       567005     71053                  WHITE METAL LANTERN        12
4       573512    84029G  KNITTED UNION FLAG HOT WATER BOTTLE        15
9       547022     71053                  WHITE METAL LANTERN         7
...        ...       ...                                  ...       ...
1603    549401     21730    GLASS STAR FROSTED T-LIGHT HOLDER         5
1607    546730     21730    GLASS STAR FROSTED T-LIGHT HOLDER        14
1608    556479     22423             REGENCY CAKESTAND 3 TIER        13
1610    553299    85123A   WHITE HANGING HEART T-LIGHT HOLDER         8
1611    537515    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6

              InvoiceDate  UnitPrice  CustomerID   Country
0     2011-09-15 15:26:00       4.07     16640.0    Sweden
1     2011-06-05 08:10:00       4.25     17154.0    Sweden
3     2011-09-04 16:55:00       3.39     14222.0     Spain
4     2011-02-23 13:40:00       3.39     16830.0    Sweden
9     2011-09-14 17:41:00       4.07     15256.0      EIRE
...                   ...        ...         ...       ...
1603  2011-05-25 22:09:00       3.40     13436.0  Portugal
1607  2011-09-20 00:21:00       4.25     16326.0     Spain
1608  2011-11-13 09:05:00      12.75     13615.0      EIRE
1610  2011-09-24 16:24:00       2.55     17478.0  Portugal
1611  2011-08-24 00:48:00       2.55     17296.0   Germany

[1151 rows x 8 columns]
Total matching transactions: 1151

In [17]:
#29.	Use query to find transactions where Quantity is greater than 10 and UnitPrice is greater than £5.

filtered_df = df.query("Quantity > 10 and UnitPrice > 5")
print("Transactions with Quantity > 10 and UnitPrice > 5:")
display(filtered_df)
print("Total matching transactions:", len(filtered_df))

Transactions with Quantity > 10 and UnitPrice > 5:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
18,580659,79323P,PINK CHERRY LIGHTS,15,2011-06-11 21:15:00,8.10,18019.0,Sweden
31,550785,22423,REGENCY CAKESTAND 3 TIER,15,2011-09-25 21:14:00,12.75,16898.0,Netherlands
38,566325,22423,REGENCY CAKESTAND 3 TIER,11,2011-01-14 18:07:00,10.20,13528.0,Sweden
69,566686,22423,REGENCY CAKESTAND 3 TIER,13,2011-06-14 08:46:00,12.75,15782.0,United Kingdom
89,577425,22752,SET 7 BABUSHKA NESTING BOXES,14,2011-11-16 02:46:00,6.12,16327.0,Sweden
...,...,...,...,...,...,...,...,...
1575,547919,22423,REGENCY CAKESTAND 3 TIER,11,2011-04-09 18:38:00,12.75,16277.0,EIRE
1587,572765,21730,GLASS STAR FROSTED T-LIGHT HOLDER,15,2010-12-12 17:20:00,5.10,17421.0,Belgium
1595,564607,POST,POSTAGE,15,2011-07-02 04:57:00,18.00,13500.0,Netherlands
1601,540834,POST,POSTAGE,14,2011-01-26 11:06:00,21.60,13594.0,United Kingdom
1608,556479,22423,REGENCY CAKESTAND 3 TIER,13,2011-11-13 09:05:00,12.75,13615.0,EIRE

Total matching transactions: 203

In [18]:
#30.	Sort transactions by UnitPrice in descending order and display the 20 highest unit-price records.
sorted_df = df.sort_values(by="UnitPrice",ascending=False)
top_20 = sorted_df.head(20)

print("20 transactions with the highest unit prices:")
display(top_20)

print("Number of records displayed:", len(top_20))

20 transactions with the highest unit prices:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1248,565100,POST,POSTAGE,14,2011-11-25 20:27:00,21.6,13873.0,Australia
1253,573477,POST,POSTAGE,8,2011-04-22 14:47:00,21.6,18172.0,EIRE
49,557529,POST,POSTAGE,7,2011-08-19 06:38:00,21.6,17690.0,Australia
465,569506,POST,POSTAGE,6,2011-11-08 11:22:00,21.6,16513.0,Australia
932,C561717,POST,POSTAGE,-11,2011-11-22 12:10:00,21.6,15675.0,Netherlands
1528,565108,POST,POSTAGE,10,2011-03-29 08:51:00,21.6,16176.0,France
1560,567925,POST,POSTAGE,4,2011-01-20 13:21:00,21.6,17041.0,France
101,573603,POST,POSTAGE,8,2011-03-16 11:27:00,21.6,14863.0,Australia
764,572968,POST,POSTAGE,6,2011-07-22 19:28:00,21.6,16251.0,Germany
502,C543573,POST,POSTAGE,-15,2011-05-26 09:37:00,21.6,17799.0,Spain
833,574836,POST,POSTAGE,2,2011-05-21 21:25:00,21.6,14562.0,EIRE
501,552616,POST,POSTAGE,6,2011-05-15 13:37:00,21.6,12473.0,France
752,549960,POST,POSTAGE,15,2011-10-20 05:17:00,21.6,14865.0,Australia
353,570905,POST,POSTAGE,12,2011-05-18 16:49:00,21.6,NaN,United Kingdom
359,547600,POST,POSTAGE,8,2011-10-08 10:31:00,21.6,14477.0,Portugal
456,578392,POST,POSTAGE,1,2010-12-16 14:40:00,21.6,15550.0,Germany
1601,540834,POST,POSTAGE,14,2011-01-26 11:06:00,21.6,13594.0,United Kingdom
7,574557,POST,POSTAGE,1,2011-09-23 07:36:00,21.6,13566.0,France
617,540834,POST,POSTAGE,14,2011-01-26 11:06:00,21.6,13594.0,United Kingdom
893,565522,POST,POSTAGE,1,2011-08-02 16:33:00,21.6,13623.0,United Kingdom

Number of records displayed: 20